version: "2"

services:
  pi-inline-ase:
    image: docker-registry.pi-su2020.com:5000/pingidentity/ase:${PI_VERSION}
    env_file:
      - ./inline_env_vars
    shm_size: 1g
    ports:
      - 8010:8010
      - 8443:8443
      - 8080:8080
    networks:
      - pingnet

#  pi-aad-amt:
#    image: docker-registry.pi-su2020.com:5000/pingidentity/aad_amt:${PI_VERSION}
#    env_file:
#      - ./inline_env_vars
#    networks:
#      - pingnet

networks:
    pingnet:
